### ISSUE TITLE
UI Mockup

### ISSUE THREAD

**Issue by seisure** [seisure/ASE#20]
evtl. Balsamiq

**Comment by jimtoniq** [comment]
![export](https://user-images.githubusercontent.com/36745144/49245234-06794680-f412-11e8-97d0-28b0dd8d0b7c.png)

**Comment by jimtoniq** [comment]
![about](https://user-images.githubusercontent.com/36745144/49250312-cc627180-f41e-11e8-8f6b-72e5f9b5f75f.png)

**Comment by jimtoniq** [comment]
![google pixel 2](https://user-images.githubusercontent.com/36745144/49343113-3029ac00-f664-11e8-8f58-ad5a8aa1f8c9.png)

**Comment by jimtoniq** [comment]
![table](https://user-images.githubusercontent.com/36745144/49343122-48013000-f664-11e8-868f-aeee5d9056ae.png)
