### ISSUE TITLE
Seite erstellen mit Erklärung der App

### ISSUE THREAD

**Issue by twildber** [seisure/ASE#87]
#86

**Comment by jimtoniq** [comment]
![a](https://user-images.githubusercontent.com/36745144/49371793-f0f96a80-f6f8-11e8-8bf0-eb919e06720e.png)
Klicke auf +A, um eine neue Aktion zur Entscheidungstabelle hinzuzufügen.

![b](https://user-images.githubusercontent.com/36745144/49371794-f0f96a80-f6f8-11e8-8ece-35a396bec320.png)
Klicke auf +B, um eine neue Bedingung zur Entscheidungstabelle hinzuzufügen.
![r](https://user-images.githubusercontent.com/36745144/49371795-f0f96a80-f6f8-11e8-80a9-1957477c3879.png)
Klicke auf +R, um eine neue Regel zur Entscheidungstabelle hinzuzufügen.


![screenshot_20181203-124021](https://user-images.githubusercontent.com/36745144/49372101-dd023880-f6f9-11e8-8986-76c34fecac32.png)

Um die Tabelle ganzheitlich zu bearbeiten oder eine vorhandene Tabelle zu importieren, klicke auf "Tabelle bearbeiten".

Über "Exportieren" kann die aktuelle Entscheidungstabelle als Java-Code, C#-Code oder als CSV-Datei exportiert werden.

Klicke auf "Alles löschen" um von neu zu beginnen.

Informationen über die App erhälst du unter "App-Info"

**Comment by jimtoniq** [comment]
Wir haben dir für den Anfang schon mal eine Tabelle angelegt.
