### ISSUE TITLE
Der Benutzer darf keine Tabelle mit nur jew. einer Bedingung, Aktion und Regel anlegen können

### ISSUE THREAD

**Issue by twildber** [seisure/ASE#95]
Der Default-Zustand besteht aus 1 Regel, 1 Aktion, 1 Bedingung.

**Comment by twildber** [comment]
#94

**Comment by jimtoniq** [comment]
Der Startbildschirm ist wie besprochen die Entscheidungstabelle.
Um den initialen Zustand zu erreichen, fügen wir in das HowTo eine Erklärung ein, dass bereits für den Start eine Tabelle angelegt wurde.
